### ISSUE TITLE
multi level pointer(read_kernel_memory probleme)

### ISSUE THREAD

**Issue by Ahora57** [kkent030315/libmhyprot#3]
So, I decided to try test your library on something lightweight. I decided to try to make a FindDMAAddy wrapper for a multi level pointer. But its just work:addr + offset. Cane you help with this? I feel stupid and i dont understand why its just dont work
// FindDMAAddy wrapper  https://pastebin.com/LMv9T8fT

```cpp
uintptr_t FindDMAAddy( uint32_t target_process_id ,const uintptr_t ptr, std::vector<unsigned int> offsets)
{
     uint64_t addr = ptr; 
    for (unsigned int i = 0; i < offsets.size(); ++i)
    {
        libmhyprot::read_process_memory(target_process_id, addr, (BYTE*)addr,sizeof(addr));
       
        addr += offsets[i];
    }
    return addr;
}
```

**Comment by Ahora57** [comment]
I managed to figure it out. Sorry for the stupid question and post.

**Comment by kkent030315** [comment]
To acquire pointer of a pointer of a pointer...
Here is the example:

```cpp
uint64_t foo( const uint32_t& pid, const std::vector< uint64_t >& chain )
{
	uint64_t result = chain[ 0 ];

	for ( auto i = 1u; i < chain.size(); i++ )
	{
		if ( !result ) break;
		result = libmhyprot::read_process_memory< uint64_t >( pid, result + chain[ i ] );
	}

	return result;
}
```

```cpp
foo( 19944, { 0xBASEADDRESS, 0xAA, 0xBB, 0xCC } );
```

**Comment by Ahora57** [comment]
My problem was with uintptr_t for addr/result (need use DWORD for this). Unfortunately, I did not notice this at night when I became interested in this library. Anyway, thanks for the answer.
