### ISSUE TITLE
Failing to prepare (0x20)

### ISSUE THREAD

**Issue by destinybeholdsup** [kkent030315/libmhyprot#4]
First time dealing with this type of stuff and when I go to load my program, it's failing to prepare "mhyprot.sys".
The error code it's giving me is 0x20.

I'm on windows 10 20H2 (OS Build 19042.1052)

**Comment by kkent030315** [comment]
Referer MSDN: https://docs.microsoft.com/ja-jp/windows/win32/debug/system-error-codes--0-499-
ox20 is an error of `ERROR_SHARING_VIOLATION `

**Comment by kkent030315** [comment]
There is no chance to trigger `ERROR_SHARING_VIOLATION ` usually so I assume it's `ERROR_BAD_UNIT (0x14 decimal 20)` as the MSDN says: 

> The system cannot find the device specified.

**Comment by destinybeholdsup** [comment]
> There is no chance to trigger `ERROR_SHARING_VIOLATION ` usually so I assume it's `ERROR_BAD_UNIT (0x14 decimal 20)` as the MSDN says:
> 
> > The system cannot find the device specified.

Do you have an idea why it would be causing `ERROR_BAD_UNIT`? I know for sure it isn't being used already since I don't have anything installed/running that would cause it to be used.

**Comment by kkent030315** [comment]
Please provide more details about exactly where and what is causing the problem, by place breakpoint, make trace log or provide callstack.
also make sure you are running the process as the administrator privilege since this lib uses service controller functionality which needs administrator privilege.

**Comment by kkent030315** [comment]
`ERROR_BAD_UNIT` could be triggered in [here](https://github.com/kkent030315/libmhyprot/blob/main/src/mhyprot.cpp#L84) which means that the mhyprot driver did not successfully started by the lib.

As I said early:

> The system cannot find the device specified.

libmhyprot couldn't open the device handle of mhyprot driver `\\\\?\\\\mhyprot2`

**Comment by destinybeholdsup** [comment]
I fixed it. I just had to re-delete the service completely and re-do it.
