### ISSUE TITLE
Some one is using your driver to make illegal cheat on the game call paladins

### ISSUE THREAD

**Issue by sunflower130420** [kkent030315/libmhyprot#5]
The driver attach the same function and has alot of code on this res 
Github: https://github.com/LagradOst/PaladinsHackPublic/tree/master/PaladinsHack/Mhyprot
UC Thread: https://www.unknowncheats.me/forum/paladins/464157-paladins-external-hack.html

**Comment by kkent030315** [comment]
EAC knows
